name: Deploy to Shopify Dev Store

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy Theme
        uses: shopify/shopify-cli-action@v3
        with:
          command: theme push --store ${{ secrets.SHOPIFY_STORE }} --allow-live
        env:
          SHOPIFY_CLI_TOKEN: ${{ secrets.SHOPIFY_TOKEN }}